 



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template and will be re-created if deleted
//	   with default implementation.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
namespace AppInterfaces.Infrastructure
{

    /// <summary>
    /// MyProject implementation of Unit of Work
    /// </summary>
	public partial interface IAppUnitOfWork
		: IUnitOfWork
	{
					
		/// <summary>
		/// Gets the BookRepository repository.
		/// </summary>
		/// <value>
		/// The BookRepository repository.
		/// </value>
     //   AppInterfaces.Repository.IBookRepository BookRepository { get; }
				
    }
}